amcl:
  ros__parameters:
    use_sim_time: false
    update_min_d: 0.2
    update_min_a: 0.2
    min_particles: 500
    max_particles: 2000
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.1

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 20.0
    min_vel_x: 0.0
    max_vel_x: 0.26
    min_vel_theta: -1.82
    max_vel_theta: 1.82
    xy_goal_tolerance: 0.25
    yaw_goal_tolerance: 0.25
    max_accel_x: 2.5
    max_accel_theta: 3.2

planner_server:
  ros__parameters:
    use_sim_time: false
    planner_frequency: 5.0
    max_planning_time: 2.0
    planner_plugins: ["GridBased"]

bt_navigator:
  ros__parameters:
    use_sim_time: false
    bt_loop_duration: 10
